### ISSUE TITLE
roadmap for `0.7.0`

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/statsExpressions#54]
- [x] use `parameters` to extract a dataframe from `onesampb`
- [ ] remove summary table here https://indrajeetpatil.github.io/statsExpressions/articles/stats_details.html#two-sample-tests-1
- [x] use `effectsize` instead of `rcompanion` to extract effect sizes for non-parametric tests
- [x] see if `effectsize` would add a column `effsize.method` to the output dataframe with more detailed description of the effect size
- [x] if `model_parameters`  returns effect sizes for non-parametric tests as well, collapse individual `expr_t_*` and `expr_anova_*` type functions to one function
- [x] move `bf_` functions to `statsExpressions` and cover them under `type` argument

**Comment by IndrajeetPatil** [comment]
remove effsize type switch function, which is not used internally anymore

**Comment by IndrajeetPatil** [comment]
Instead of using `if`, use `method` column in `model_parameters` output + `grep` to decide what quote `switch` should produce:

https://github.com/IndrajeetPatil/statsExpressions/blob/cf8247c71326a03df2acbee84ff7b2438cddbf41/R/helpers_contingency_tabs.R#L145-L150

**Comment by IndrajeetPatil** [comment]
For one-sample:

```r

if (stats.type == "parametric") {
  standardized_d <- hedges_g <- NULL

  # deciding which effect size to use (Hedge's g or Cohen's d)
  if (effsize.type %in% c("unbiased", "g")) {
    hedges_g <- TRUE
    effsize.text <- quote(widehat(italic("g"))["Hedge"])
  } else {
    standardized_d <- TRUE
    effsize.text <- quote(widehat(italic("d"))["Cohen"])
  }

  # setting up the t-test model and getting its summary
  stats_df <-
    stats::t.test(
      x = x_vec,
      mu = test.value,
      conf.level = conf.level,
      na.action = na.omit
    ) %>%
    tidy_model_parameters(.,
      standardized_d = standardized_d,
      hedges_g = hedges_g
    )

  # preparing expression parameters
  statistic.text <- quote(italic("t")["Student"])
  no.parameters <- 1L
}
```

**Comment by IndrajeetPatil** [comment]
remove this duplicated line:
https://github.com/IndrajeetPatil/statsExpressions/blob/90855970d260b1d1e305ecd8884f8fe8f922ccf4/R/helpers_expr_template.R#L255

**Comment by IndrajeetPatil** [comment]
remove all `as_tibble(.)` statements when the data is being read; this is unnecessary

**Comment by IndrajeetPatil** [comment]
Change nonparametric to robust in the read me example

**Comment by IndrajeetPatil** [comment]
don't use `stats_type` instead of `type`
